services:
  db:
    image: postgres:15
    container_name: gw-currency-wallet
    environment:
      POSTGRES_DB: gw-currency-wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data
