services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_DBNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DBNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    container_name: currency-wallet
    build:
      context: ./
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - my_network
    entrypoint: [ "./main" ]

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - TZ=UTC
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "${DATABASE_DSN}", "up" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

volumes:
  redis_data:
    driver: local

networks:
  my_network:
    external: true
