services:
  db:
    image: postgres:15
    container_name: gw-currency-wallet
    environment:
      POSTGRES_DB: gw-currency-wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: test-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--requirepass", "your_secure_password",
      "--save", "",                 # ❌ Отключает RDB (снимки)
      "--appendonly", "no"          # ❌ Отключает AOF (журнал команд)
    ]
    environment:
      - TZ=UTC
